String baseUrl = 'https://teleseha.com/api/';

// ******************** KEYS ********************

const String keyName = 'Name';
const String keySelectedIcon = 'selected_icon';
const String keyTitle = 'title';
const String mobile = 'mobile';
const String otp = 'otp';
const String password = 'password';
const String createPasswordToken = 'createPasswordToken';
const String myRefreshToken = 'refreshToken';
const String date = 'BirthDate';
const String isMale = 'IsMale';
const String maritalStatus = 'MaritalStatus';
const String jobTitle = 'JobTitle';
const String myState = 'State';
const String city = 'City';
const String cityId = 'CityId';
const String patientId = 'patientId';
const String section = 'section';
const String subSections = 'sub-sections';
const String id = 'id';
const String title = 'title';
const String subSection = 'sub-sections';
const String items = 'items';
const String item = 'item';
const String message = 'message';
const String file = 'file';
const String messageType = 'messageType';
const String checkUpId = 'checkUpId';
const String rating = 'rating';
const String review = 'review';
const String callTimeRating = 'call_time_rating';
const String isFirstAdvantage = 'is_first_advantage';
const String isSecondAdvantage = 'is_second_advantage';
const String isThirdAdvantage = 'is_third_advantage';
const String checkupId = 'checkup_id';
const String doctorId = 'doctor_id';
